/* Generated by gensqlstatehashfunc.c on Wed Jul 30 14:17:23 2014
 */
#define HASH_SQLSTATE_MODULO 1409
static inline unsigned int
hash_sqlstate(unsigned int s)
{
  s ^= s >> 16;
  s *= 0x85ebca6b + 45;
  s ^= s >> 13;
  s *= 0xc2b2ae35 + 5610;
  s ^= s >> 16;
  return s % HASH_SQLSTATE_MODULO;
}
